behaviors:
  GhostReach:
    trainer_type: ppo
    hyperparameters:
      batch_size: 1024
      buffer_size: 10240
      learning_rate: 0.0003
      beta: 0.005
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 3
      learning_rate_schedule: linear
      shared_critic: False
    network_settings:
      normalize: False
      hidden_units: 1024
      num_layers: 2
      vis_encode_type: simple
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
    behavioral_cloning:
      demo_path: C:\Users\koh2040\Desktop\CTP499_Pacman\Assets\Demonstrations\task5demo20000.demo
      strength: 0.5
      steps: 20000
      samples_per_update: 512
    keep_checkpoints: 5
    checkpoint_interval: 5000
    max_steps: 2500000
    time_horizon: 64
    summary_freq: 5000
