behaviors:
  GhostReach:
    trainer_type: ppo
    hyperparameters:
      batch_size: 1024
      buffer_size: 10240
      learning_rate: 0.0003
      beta: 0.005
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 3
      learning_rate_schedule: linear
      shared_critic: False
    network_settings:
      normalize: False
      hidden_units: 1024
      num_layers: 3
      vis_encode_type: simple
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
    behavioral_cloning:
      demo_path: 
      strength: 0.3
      steps: 40000
      samples_per_update: 0
    keep_checkpoints: 5
    checkpoint_interval: 5000
    max_steps: 750000
    time_horizon: 128
    summary_freq: 5000
